linksharing/handler: errors if prefix listing path doesn't end in /
storj/linksharing pull request #12
Opened 2020-09-25 01:12 UTC by jenlij

2020-09-25 13:26 UTC, calebcase commented
The PR makes me think we can make a better UX since we can detect when the mistake has happened. When we detect that a listing should have been requested with a trailing slash we could either 1) send a 301 redirect to the client or 2) fix up the URL path so that the rest of the path constructions work as intended. Either of those feel better than returning an error to the user to me.

2020-09-25 18:15 UTC, jenlij commented
Let me see if I can create the redirect. Otherwise, I would like it if we returned an error rather than allow the current behavior until we can fix the URL issue on the server side.

2020-09-25 20:36 UTC, calebcase submitted a review, later dismissed

2020-09-26 00:58 UTC, calebcase approved these changes

2020-09-28 06:29 UTC, egonelbre requested changes

2020-09-28 06:29 UTC, egonelbre commented on linksharing/handler.go
> +			http.Redirect(w, r, r.URL.Path+"/", http.StatusMovedPermanently)
return is missing, unless you want to serve the error page as well?

2020-09-29 20:46 UTC, calebcase approved these changes

2020-09-30 07:14 UTC, egonelbre approved these changes

2020-09-30 19:44 UTC, calebcase approved these changes

2020-09-30 19:59 UTC, egonelbre approved these changes

2020-09-30 20:00 UTC, merged